---
# file roles/nginx/tasks/main.yml

- name: add nginx repo
  shell: echo "deb http://ppa.launchpad.net/nginx/stable/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/nginx-stable.list
  sudo: yes

#- name: add keyserver 
#  shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C300EE8C
#  sudo: yes

- name: add keyserver 
  apt_key: keyserver=keyserver.ubuntu.com id=C300EE8C
  sudo: yes

- name: udpate apt  
  apt: update_cache=yes
  sudo: yes

- name: install nginx
  apt: name="nginx" state=present
  sudo: yes

